server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: eurka-feign

feign: # Feign是自带断路器,配置断路器为true
  hystrix:
    enabled: true

