server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: eurka-zuul
  main:
    allow-bean-definition-overriding: true #允许相同key情况下beanDefinition实例的覆盖


zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: eurka-ribbon
    feign:
      path: /feign/**
      serviceId: eurka-feign

